[package]
name = "lstty"
description = "A simple terminal tool to list serial ports"
authors = ["atctwo", "igiona"]
version = "0.2.0"
edition = "2024"
readme = "readme.md"
repository = "https://github.com/atctwo/lstty"
license = "MIT"
keywords = ["terminal"]
categories = ["command-line-utilities"]

[[bin]]
name = "lstty"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
clap-num = "1.2.0"
log = "0.4.29"
logging = "0.1.0"
pretty_env_logger = "0.5.0"
serialport = "4.8.1"
